[package]
name = "cs336_basics_rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "cs336_basics_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
